### ISSUE TITLE
TFAR Radios disappear shortly after equipping

### ISSUE THREAD

**Issue by MrDj200** [tbox1911/Liberation-RX#134]
Hi, 
when I equip a TFAR Radio, it disappears shortly after.
Am I missing a compat mod or similar?

**Comment by tbox1911** [comment]
hi,
this issue should be fixed in latest build, 

could you update and retry please ?

**Comment by MrDj200** [comment]
I've updated but it's still not fixed.

And the radios still seem to be the old ones:
![image](https://github.com/tbox1911/Liberation-RX/assets/5685500/d1a3ef8c-d4fe-40e8-8492-b8de4d2e714a)

Equipping the Radio that's just called `Radio` assigns a radio but that is also taken away after a few seconds

**Comment by MrDj200** [comment]
It seems to only happen when the mission is running on my server. Is this maybe a TFAR issue?
It works fine when I host the mission locally

**Comment by MrDj200** [comment]
Could you push a new Release so I can test it properly?

**Comment by tbox1911** [comment]
new build include your fix, please test again

**Comment by MrDj200** [comment]
yeah, works. Sorry forgot to close the issue^^
thanks

**Comment by MrDj200** [comment]
yeah, works. Sorry forgot to close the issue^^
thanks
