### ISSUE TITLE
Shots on the unconscious body

### ISSUE THREAD

**Issue by Maciccio** [tbox1911/Liberation-RX#176]
I don't quite understand when it happens, often when restarting the server, or maybe when doing certain things as Admin, when the enemies make you unconscious, they continue to shoot at you, using up all their magazines. And it's not nice to see

**Comment by Maciccio** [comment]
Today the enemies were not shooting at me when I was unconscious. When I activated Headlessclient they started shooting at me again non-stop

**Comment by Maciccio** [comment]
I confirm. I have done several tests. When enemy soldiers are loaded on the HC they shoot you endlessly

**Comment by tbox1911** [comment]
hi, thank a lot for feedback,

I'll check the headless client code

I keep you in touch

**Comment by tbox1911** [comment]
should be fixed in next release :)

**Comment by Maciccio** [comment]
> should be fixed in next release :)

My server is waiting for this update, thanks 😍😘

**Comment by tbox1911** [comment]
try with latest version v2.6.11, should be fixed

(enemies can still fire at you a little, but disengage after a while)

**Comment by Maciccio** [comment]
> try with latest version v2.6.11, should be fixed
> 
> (enemies can still fire at you a little, but disengage after a while)

Hi.
I deleted all the .vars saves and reset the mission with Wipesavegame but the problem persists, the enemies continue to shoot you relentlessly 😢

**Comment by Maciccio** [comment]
Hello.
I also tried the latest update but it doesn't work for me.
If you want I can give you the admin of my server to try, I don't want it to be just my problem

**Comment by tbox1911** [comment]
I still investigate this issue, seem to be in the Arma engine itself.

I try to find a workaround

**Comment by Maciccio** [comment]
Yesssssssssssssssssssssssssssssssssssssssss. It finally works. Thank you <3
